[package]
name = "libikarus-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.152"
serde_derive = "1.0.152"
serde_yaml = "0.9.17"
anyhow = "1.0.68"
# walkdir would suffice but has more dependencies
glob = "0.3.1"